# Generated by Django 5.0.3 on 2024-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_article_author_article_header_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.TextField(default=''),
        ),
    ]
