# Generated by Django 5.0.3 on 2024-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_comment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(choices=[('LP', 'Laptops'), ('PH', 'Phones'), ('PR', 'Processors'), ('KB', 'Keyboards'), ('TV', 'Televisions')], max_length=255),
        ),
    ]
