# Generated by Django 5.0.3 on 2024-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_articlecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(choices=[('LAPTOPS', 'Laptops'), ('PHONES', 'Phones'), ('PROCESSORS', 'Processors'), ('KEYBOARDS', 'Keyboards'), ('TELEVISIONS', 'Televisions')], default='TV', max_length=255),
        ),
    ]
