# Generated by Django 4.2.11 on 2024-05-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile'),
        ('wiki', '0007_alter_article_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_author', to='user_management.profile'),
        ),
    ]
