# Generated by Django 5.0.3 on 2024-03-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('people_required', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='commissions.commission')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
