# Generated by Django 5.0.3 on 2024-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commission_people_required_commission_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-commission_status', '-created_on']},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='status',
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('FULL', 'FULL'), ('COMPLETED', 'COMPLETED'), ('DISCONTINUED', 'DISCONTINUED')], default='OPEN', max_length=15),
        ),
    ]
