# Generated by Django 5.0.3 on 2024-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_commission_options_remove_commission_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['job_status', '-manpower', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['application_status', '-applied_on']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('FULL', 'FULL')], default='open', max_length=5),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('pend', 'PENDING'), ('accept', 'ACCEPTED'), ('reject', 'REJECTED')], default='pend', max_length=6),
        ),
    ]
