# Generated by Django 5.0.3 on 2024-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_alter_commission_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
