# Generated by Django 5.0.3 on 2024-05-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_alter_job_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['commission_status', '-created_on']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('FULL', 'FULL'), ('GCOMPLETED', 'GCOMPLETED'), ('DISCONTINUED', 'DISCONTINUED')], default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
