# Generated by Django 4.2.11 on 2024-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-commission_status', '-created_on']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('FULL', 'FULL'), ('ECOMPLETED', 'COMPLETED'), ('DISCONTINUED', 'DISCONTINUED')], default='OPEN', max_length=15),
        ),
    ]
