# Generated by Django 4.2.11 on 2024-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-job_status', '-manpower', 'role']},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('APENDING', 'PENDING'), ('BACCEPTED', 'ACCEPTED'), ('CREJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
